sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

cache:
  directories:
    - node_modules/

jobs:
  include:
    - script: npm run tslint
    - script: npm run build-release
    - script: ./mkDocs.sh